# Generated by Django 3.0.2 on 2020-01-19 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataAccessLayer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundingsourceproperty',
            name='fundingSourceTypeId',
        ),
        migrations.AddField(
            model_name='fundingsourceproperty',
            name='fundingSourceId',
            field=models.ForeignKey(default='613b538f-db7f-4d5f-a575-944143334658', on_delete=django.db.models.deletion.CASCADE, to='DataAccessLayer.FundingSource'),
        ),
    ]
