# Generated by Django 3.0.2 on 2020-01-22 09:56

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('DataAccessLayer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuer',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='issuer',
            name='referenceType',
            field=models.CharField(choices=[('alpha-numeric', 'Containing alphabets and numbers'), ('numeric', 'Containing only numbers'), ('alpha', 'Containing only alphabets')], max_length=32),
        ),
    ]
