# Generated by Django 3.0.2 on 2020-01-22 11:48

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('DataAccessLayer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginModel',
            fields=[
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('isDeleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('userId', models.UUIDField(editable=False)),
                ('phoneNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('pin', models.CharField(blank=True, max_length=6, null=True)),
                ('Password', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='beneficiarysourceproperty',
            name='beneficiarySourcePropertyTypeId',
        ),
        migrations.AddField(
            model_name='beneficiarysourceproperty',
            name='propertyType',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.DeleteModel(
            name='BeneficiarySourcePropertyType',
        ),
    ]
