# Generated by Django 3.0.2 on 2020-01-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataAccessLayer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='firstNname',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lastNname',
            new_name='lastName',
        ),
        migrations.AlterField(
            model_name='user',
            name='userId',
            field=models.UUIDField(editable=False),
        ),
    ]
