# Generated by Django 3.0.2 on 2020-01-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataAccessLayer', '0002_auto_20200122_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiarysourcetype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
